# Problem Set 5

In [236]:
#!pip install nltk
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
from nltk.stem import PorterStemmer

## 1.
### 1 and 2

In [237]:
email = pd.read_csv("../data/lingspam-emails.csv.bz2", sep = '\t')
email = email.drop("files", axis=1)
email['spam'] = email['spam'].astype('str') 
email['message'] = email['message'].astype('str') 
email.head()

spam                                            message
0  False  Subject: re : 2 . 882 s - > np np  > date : su...
1  False  Subject: s - > np + np  the discussion of s - ...
2  False  Subject: 2 . 882 s - > np np  . . . for me it ...
3  False  Subject: gent conference  " for the listserv "...
4  False  Subject: query : causatives in korean  could a...

In [238]:
sum(email['spam'].isna())

0

In [239]:
sum(email['message'].isna())

0

In [240]:
onlySpam = email[(email['spam'] == 'True')]
noSpam = email[(email['spam'] == 'False')]
onlySpam.head(20)

spam                                            message
241  True  Subject: great part-time or summer job !  * * ...
242  True  Subject: auto insurance rates too high ?  dear...
243  True  Subject: do want the best and economical hunti...
244  True  Subject: email 57 million people for $ 99  57 ...
245  True  Subject: do n't miss these !  attention ! warn...
246  True  Subject: see amazing world record sex !  atten...
247  True  Subject: we can help you get a loan ! ! !  sub...
248  True  Subject: beat the irs & pay-no - more  = = = =...
249  True  Subject: email 57 million people for $ 99  57 ...
250  True  Subject:   make $ 3500 per week using your hom...
251  True  Subject: the best , just got better  the 2 new...
252  True  Subject: . . . . . use hypnosis to make money ...
253  True  Subject: the challenge  from the desk of rober...
254  True  Subject: * special book offer * from americana...
255  True  Subject: internet - finance / top - earnings /...
256  True  Subject: the right tools - valuable resources ...
257  True  Subject: 50 % or better returns .  federally m...
258  True  Subject: " life without debt "  pardon the int...
259  True  Subject: just released ! 10 million ! ! !  it ...
260  True  Subject: troubling credit history ? let us hel...

Viagra, deadline, million, and, sex, beat, debt, offer, special, best

## 2.
### 1.

In [241]:
list_of_words = ["viagra", "deadline", "million", "and", "sex", "beat", "debt", "offer", "special","best"]

I will use the words: Viagra, deadline, million, and, sex, beat, debt, offer, special, best
### 2.

In [242]:
import warnings
warnings.filterwarnings("ignore")
emails = pd.DataFrame()
for w in list_of_words:
    email[w] = email.message.str.lower().str.contains(w)
    email[w] = email[w].replace(True, 1)
    email[w] = email[w].replace(False, 0)
    onlySpam[w] = onlySpam.message.str.lower().str.contains(w)
    onlySpam[w] = onlySpam[w].replace(True, 1)
    onlySpam[w] = onlySpam[w].replace(False, 0)
emailsDTM = email[["viagra", "deadline", "million", "and", "sex", "beat", "debt", "offer", "special","best"]]
emailsDTM_spam = onlySpam[["viagra", "deadline", "million", "and", "sex", "beat", "debt", "offer", "special","best"]]
emailsDTM.head()

viagra  deadline  million  and  sex  beat  debt  offer  special  best
0       0         0        0    1    0     0     0      0        0     0
1       0         0        0    0    0     0     0      0        0     0
2       0         0        0    0    0     0     0      0        0     0
3       0         0        0    1    0     0     0      0        1     0
4       0         0        0    1    0     0     0      0        0     0

### 3. 

In [243]:
from sklearn.model_selection import train_test_split
X = emailsDTM
y = (email.spam)
Xt, Xv, yt, yv, = train_test_split(X, y, test_size=0.2)

## 3. Estimate and Validate

### 1,2,3.

In [244]:
yyt = pd.DataFrame(data=yt) 
yytS = yyt[(yyt['spam'] == 'True')]
yyt['spam'] = np.where(yyt['spam'] == 'True', 1 ,0)
PrS1f = yyt.mean()
PrS1 = PrS1f[0]
PrS0 = ((len(yyt)-len(yytS))/len(yyt)) 
a = Xt.mean()
PrW1Viagra, PrW1Deadline, PrW1Million, PrW1And, PrW1Sex, PrW1Beat, PrW1Debt, PrW1Offer, PrW1Special, PrW1Best = [a[i] for i in range(10)]
PrW0Viagra, PrW0Deadline, PrW0Million, PrW0And, PrW0Sex, PrW0Beat, PrW0Debt, PrW0Offer, PrW0Special, PrW0Best = [100 - (a[i]) for i in range(10)]
other_listW1 = [PrW1Viagra, PrW1Deadline, PrW1Million, PrW1And, PrW1Sex, PrW1Beat, PrW1Debt, PrW1Offer, PrW1Special, PrW1Best]
other_listW0 = [PrW0Viagra, PrW0Deadline, PrW0Million, PrW0And, PrW0Sex, PrW0Beat, PrW0Debt, PrW0Offer, PrW0Special, PrW0Best]

### 4.

In [245]:
b1 = pd.concat([Xt,yyt],axis=1)
b2 = b1[(b1['spam'] == 1)]
b = b2.mean()
c1 = b1[(b1['spam'] == 0)]
c = c1.mean()
PrW1ViagraS1, PrW1DeadlineS1, PrW1MillionS1, PrW1AndS1, PrW1SexS1, PrW1BeatS1, PrW1DebtS1, PrW1OfferS1, PrW1SpecialS1, PrW1BestS1 = (b[i] for i in range(10))
PrW1ViagraS0, PrW1DeadlineS0, PrW1MillionS0, PrW1AndS0, PrW1SexS0, PrW1BeatS0, PrW1DebtS0, PrW1OfferS0, PrW1SpecialS0, PrW1BestS0 = (c[i] for i in range(10))
other_listS1 = [PrW1ViagraS1, PrW1DeadlineS1, PrW1MillionS1, PrW1AndS1, PrW1SexS1, PrW1BeatS1, PrW1DebtS1, PrW1OfferS1, PrW1SpecialS1, PrW1BestS1]
other_listS0 = [PrW1ViagraS0, PrW1DeadlineS0, PrW1MillionS0, PrW1AndS0, PrW1SexS0, PrW1BeatS0, PrW1DebtS0, PrW1OfferS0, PrW1SpecialS0, PrW1BestS0]

### 5.

In [246]:
PrW0S1 = np.mean((Xt ==0)[yt == 'True'])
PrW0S1Viagra, PrW0S1Deadline, PrW0S1Million, PrW0S1And, PrW0S1Sex, PrW0S1Beat, PrW0S1Debt, PrW0S1Offer, PrW0S1Special, PrW0S1Best = (PrW0S1[i] for i in range(10))
other_listW0S1 = [PrW0S1Viagra, PrW0S1Deadline, PrW0S1Million, PrW0S1And, PrW0S1Sex, PrW0S1Beat, PrW0S1Debt, PrW0S1Offer, PrW0S1Special, PrW0S1Best]
PrS1W1Viagra, PrS1W1Deadline, PrS1W1Million, PrS1W1And, PrS1W1Sex, PrS1W1Beat, PrS1W1Debt, PrS1W1Offer, PrS1W1Special, PrS1W1Best = ((other_listS1[i] * PrS1) / other_listW1[i] for i in range(10))
PrS1W0Viagra, PrS1W0Deadline, PrS1W0Million, PrS1W0And, PrS1W0Sex, PrS1W0Beat, PrS1W0Debt, PrS1W0Offer, PrS1W0Special, PrS0W1Best = ((other_listW0S1[i] * PrS1) / other_listW0[i] for i in range(10))
list_S1W1 = [PrS1W1Viagra, PrS1W1Deadline, PrS1W1Million, PrS1W1And, PrS1W1Sex, PrS1W1Beat, PrS1W1Debt, PrS1W1Offer, PrS1W1Special, PrS1W1Best]
list_S1W0 = [PrS1W0Viagra, PrS1W0Deadline, PrS1W0Million, PrS1W0And, PrS1W0Sex, PrS1W0Beat, PrS1W0Debt, PrS1W0Offer, PrS1W0Special, PrS0W1Best]

### 6.
- Pr(category =S1|w=1) + Pr(category =S0|w=1) = 1, Pr(category =S1|w=0) + Pr(category =S0|w=0) = 1, Pr(w=1) + Pr(w=0) = 1, Pr(category=S1) + Pr(category=S0) =1 
These must sum to 1 because each probability is the inverse of each other, they're based on the same groups.
- Pr(w=1|category =S1) + Pr(w=1|category =S0) != 1, Pr(category =S0|w=1) + Pr(category =S0|w=0) != 1
These don't have to sum to 1, as the probabilities are not based on the same group.

### 7.

In [265]:
for word in list_of_words:
    Xv["Pr_" + word] = np.where(Xv[word] == 1, list_S1W1[list_of_words.index(word)],[list_S1W0[list_of_words.index(word)]])
predictions = Xv[['Pr_viagra', 'Pr_deadline', 'Pr_million', 'Pr_and',
       'Pr_sex', 'Pr_beat', 'Pr_debt', 'Pr_offer', 'Pr_special', 'Pr_best']]
predictions['Pred_viagra']=np.where(predictions['Pr_viagra'] > 0.5, 1, 0)
predictions['Pred_deadline']=np.where(predictions['Pr_deadline'] > 0.5, 1, 0)
predictions['Pred_million']=np.where(predictions['Pr_million'] > 0.5, 1, 0)
predictions['Pred_and']=np.where(predictions['Pr_and'] > 0.5, 1, 0)
predictions['Pred_sex']=np.where(predictions['Pr_sex'] > 0.5, 1, 0)
predictions['Pred_beat']=np.where(predictions['Pr_beat'] > 0.5, 1, 0)
predictions['Pred_debt']=np.where(predictions['Pr_debt'] > 0.5, 1, 0)
predictions['Pred_offer']=np.where(predictions['Pr_offer'] > 0.5, 1, 0)
predictions['Pred_special']=np.where(predictions['Pr_special'] > 0.5, 1, 0)
predictions['Pred_best']=np.where(predictions['Pr_best'] > 0.5, 1, 0)
predictions = predictions[['Pred_viagra',	'Pred_deadline',	'Pred_million',	'Pred_and',	'Pred_sex',	'Pred_beat',	'Pred_debt',	'Pred_offer',	'Pred_special',	'Pred_best']]


[1.0,
 0.0,
 0.8245614035087719,
 0.16384439359267736,
 0.35151515151515156,
 0.5161290322580645,
 0.894736842105263,
 0.41714285714285715,
 0.18494271685761052,
 0.4912891986062718]

In [248]:
predictions.columns

Index(['Pred_viagra', 'Pred_deadline', 'Pred_million', 'Pred_and', 'Pred_sex',
       'Pred_beat', 'Pred_debt', 'Pred_offer', 'Pred_special', 'Pred_best'],
      dtype='object')

### 8.

In [249]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
nyv = yv.to_frame()
nyv['spam'] = np.where(nyv['spam'] == 'True', 1 ,0)
PViagra, PDeadline, PMillion, PAnd, PSex, PBeat, PDebt, POffer, PSpecial, PBest = (predictions[column] for column in predictions)
act = nyv["spam"]
for column in predictions:
    cm = confusion_matrix(act,predictions[column], labels=[1,0])
    print(column, ":", '\n',cm)

Pred_viagra : 
 [[  0  94]
 [  0 485]]
Pred_deadline : 
 [[  0  94]
 [  0 485]]
Pred_million : 
 [[ 22  72]
 [  4 481]]
Pred_and : 
 [[  0  94]
 [  0 485]]
Pred_sex : 
 [[  0  94]
 [  0 485]]
Pred_beat : 
 [[  4  90]
 [  7 478]]
Pred_debt : 
 [[  8  86]
 [  2 483]]
Pred_offer : 
 [[  0  94]
 [  0 485]]
Pred_special : 
 [[  0  94]
 [  0 485]]
Pred_best : 
 [[  0  94]
 [  0 485]]


In [250]:
for column in predictions:
    accuracy = accuracy_score(act, predictions[column])
    recall = recall_score(act, predictions[column])
    precision = precision_score(act,predictions[column])
    print(column,'accuracy',accuracy,'precision:', precision,'recall', recall)

Pred_viagra accuracy 0.8376511226252159 precision: 0.0 recall 0.0
Pred_deadline accuracy 0.8376511226252159 precision: 0.0 recall 0.0
Pred_million accuracy 0.8687392055267703 precision: 0.8461538461538461 recall 0.23404255319148937
Pred_and accuracy 0.8376511226252159 precision: 0.0 recall 0.0
Pred_sex accuracy 0.8376511226252159 precision: 0.0 recall 0.0
Pred_beat accuracy 0.8324697754749568 precision: 0.36363636363636365 recall 0.0425531914893617
Pred_debt accuracy 0.8480138169257341 precision: 0.8 recall 0.0851063829787234
Pred_offer accuracy 0.8376511226252159 precision: 0.0 recall 0.0
Pred_special accuracy 0.8376511226252159 precision: 0.0 recall 0.0
Pred_best accuracy 0.8376511226252159 precision: 0.0 recall 0.0


### 9.

In this case, the training model is the data we gathered from the dataset, email. We used the training model in all our probability calculations to make the model, and then we used the validation to test our model, which seems to be 86% accurate. 
### 10.

The accuracy score was about 81.6%, the precisionw was about 45.7%, and the recall was about 38.4%.

### 11.
We see a low recall because we didn't identify all the true spam's correctly. Our model is obviously flawed becuase it marks emails with certain words as spam immidiately without considering any other factors.

### 12.
Million improves accuracy becuase there's more spam emails with the word million in it. Viagra doesn't work because there were no emails with viagra in them in the validation data. None of the emails with deadline in them were spam. And did not work because there were so many emails that contained the word and.
### 13./14.

dont run again:

In [251]:
df2 = {'viagra': 0, 'deadline':0, 'million': 0, 'and':0, 'sex':0,'beat':0,'debt':0,'offer':0,'special':0,'best':0}
df3 = {'viagra': 1, 'deadline':1, 'million':1, 'and': 1, 'sex':1,'beat':1,'debt':1,'offer':1,'special':1,'best':1}
Xv = Xv.append(df2, ignore_index = True)
Xv = Xv.append(df3, ignore_index = True)

In [252]:
Xv.tail(5)

viagra  deadline  million  and  sex  beat  debt  offer  special  best  \
576     0.0       0.0      0.0  1.0  0.0   0.0   0.0    0.0      0.0   0.0   
577     0.0       0.0      0.0  1.0  0.0   0.0   0.0    0.0      1.0   0.0   
578     0.0       0.0      0.0  1.0  0.0   0.0   0.0    0.0      0.0   0.0   
579     0.0       0.0      0.0  0.0  0.0   0.0   0.0    0.0      0.0   0.0   
580     1.0       1.0      1.0  1.0  1.0   1.0   1.0    1.0      1.0   1.0   

     Pr_viagra  Pr_deadline  Pr_million    Pr_and    Pr_sex   Pr_beat  \
576   0.001668     0.001675    0.001267  0.163844  0.001423  0.001603   
577   0.001668     0.001675    0.001267  0.163844  0.001423  0.001603   
578   0.001668     0.001675    0.001267  0.163844  0.001423  0.001603   
579        NaN          NaN         NaN       NaN       NaN       NaN   
580        NaN          NaN         NaN       NaN       NaN       NaN   

      Pr_debt  Pr_offer  Pr_special   Pr_best  
576  0.001526  0.001043    0.001187  0.001064  
577  0.001526  0.001043    0.184943  0.001064  
578  0.001526  0.001043    0.001187  0.001064  
579       NaN       NaN         NaN       NaN  
580       NaN       NaN         NaN       NaN

In [253]:
yyt = pd.DataFrame(data=yt) 
yytS = yyt[(yyt['spam'] == 'True')]
yyt['spam'] = np.where(yyt['spam'] == 'True', 1 ,0)
PrS1f = yyt.mean()
PrS1 = PrS1f[0]
PrS0 = ((len(yyt)-len(yytS))/len(yyt)) 
a = Xt.mean()
PrW1Viagra, PrW1Deadline, PrW1Million, PrW1And, PrW1Sex, PrW1Beat, PrW1Debt, PrW1Offer, PrW1Special, PrW1Best = [a[i] for i in range(10)]
PrW0Viagra, PrW0Deadline, PrW0Million, PrW0And, PrW0Sex, PrW0Beat, PrW0Debt, PrW0Offer, PrW0Special, PrW0Best = [100 - (a[i]) for i in range(10)]
other_listW1 = [PrW1Viagra, PrW1Deadline, PrW1Million, PrW1And, PrW1Sex, PrW1Beat, PrW1Debt, PrW1Offer, PrW1Special, PrW1Best]
other_listW0 = [PrW0Viagra, PrW0Deadline, PrW0Million, PrW0And, PrW0Sex, PrW0Beat, PrW0Debt, PrW0Offer, PrW0Special, PrW0Best]

b1 = pd.concat([Xt,yyt],axis=1)
b2 = b1[(b1['spam'] == 1)]
b = b2.mean()
c1 = b1[(b1['spam'] == 0)]
c = c1.mean()
PrW1ViagraS1, PrW1DeadlineS1, PrW1MillionS1, PrW1AndS1, PrW1SexS1, PrW1BeatS1, PrW1DebtS1, PrW1OfferS1, PrW1SpecialS1, PrW1BestS1 = (b[i] for i in range(10))
PrW1ViagraS0, PrW1DeadlineS0, PrW1MillionS0, PrW1AndS0, PrW1SexS0, PrW1BeatS0, PrW1DebtS0, PrW1OfferS0, PrW1SpecialS0, PrW1BestS0 = (c[i] for i in range(10))
other_listS1 = [PrW1ViagraS1, PrW1DeadlineS1, PrW1MillionS1, PrW1AndS1, PrW1SexS1, PrW1BeatS1, PrW1DebtS1, PrW1OfferS1, PrW1SpecialS1, PrW1BestS1]
other_listS0 = [PrW1ViagraS0, PrW1DeadlineS0, PrW1MillionS0, PrW1AndS0, PrW1SexS0, PrW1BeatS0, PrW1DebtS0, PrW1OfferS0, PrW1SpecialS0, PrW1BestS0]

PrW0S1 = np.mean((Xt ==0)[yt == 'True'])
PrW0S1Viagra, PrW0S1Deadline, PrW0S1Million, PrW0S1And, PrW0S1Sex, PrW0S1Beat, PrW0S1Debt, PrW0S1Offer, PrW0S1Special, PrW0S1Best = (PrW0S1[i] for i in range(10))
other_listW0S1 = [PrW0S1Viagra, PrW0S1Deadline, PrW0S1Million, PrW0S1And, PrW0S1Sex, PrW0S1Beat, PrW0S1Debt, PrW0S1Offer, PrW0S1Special, PrW0S1Best]
PrS1W1Viagra, PrS1W1Deadline, PrS1W1Million, PrS1W1And, PrS1W1Sex, PrS1W1Beat, PrS1W1Debt, PrS1W1Offer, PrS1W1Special, PrS1W1Best = ((other_listS1[i] * PrS1) / other_listW1[i] for i in range(10))
PrS1W0Viagra, PrS1W0Deadline, PrS1W0Million, PrS1W0And, PrS1W0Sex, PrS1W0Beat, PrS1W0Debt, PrS1W0Offer, PrS1W0Special, PrS0W1Best = ((other_listW0S1[i] * PrS1) / other_listW0[i] for i in range(10))
list_S1W1 = [PrS1W1Viagra, PrS1W1Deadline, PrS1W1Million, PrS1W1And, PrS1W1Sex, PrS1W1Beat, PrS1W1Debt, PrS1W1Offer, PrS1W1Special, PrS1W1Best]
list_S1W0 = [PrS1W0Viagra, PrS1W0Deadline, PrS1W0Million, PrS1W0And, PrS1W0Sex, PrS1W0Beat, PrS1W0Debt, PrS1W0Offer, PrS1W0Special, PrS0W1Best]

for word in list_of_words:
    Xv["Pr_" + word] = np.where(Xv[word] == 1, list_S1W1[list_of_words.index(word)],[list_S1W0[list_of_words.index(word)]])

predictions = Xv[['Pr_viagra', 'Pr_deadline', 'Pr_million', 'Pr_and',
       'Pr_sex', 'Pr_beat', 'Pr_debt', 'Pr_offer', 'Pr_special', 'Pr_best']]
predictions['Pred_viagra']=np.where(predictions['Pr_viagra'] > 0.5, 1, 0)
predictions['Pred_deadline']=np.where(predictions['Pr_deadline'] > 0.5, 1, 0)
predictions['Pred_million']=np.where(predictions['Pr_million'] > 0.5, 1, 0)
predictions['Pred_and']=np.where(predictions['Pr_and'] > 0.5, 1, 0)
predictions['Pred_sex']=np.where(predictions['Pr_sex'] > 0.5, 1, 0)
predictions['Pred_beat']=np.where(predictions['Pr_beat'] > 0.5, 1, 0)
predictions['Pred_debt']=np.where(predictions['Pr_debt'] > 0.5, 1, 0)
predictions['Pred_offer']=np.where(predictions['Pr_offer'] > 0.5, 1, 0)
predictions['Pred_special']=np.where(predictions['Pr_special'] > 0.5, 1, 0)
predictions['Pred_best']=np.where(predictions['Pr_best'] > 0.5, 1, 0)
predictions = predictions[['Pred_viagra',	'Pred_deadline',	'Pred_million',	'Pred_and',	'Pred_sex',	'Pred_beat',	'Pred_debt',	'Pred_offer',	'Pred_special',	'Pred_best']]
    
nyv = yv.to_frame()
df4 = {'spam':0}
df5 = {'spam':1}
nyv = nyv.append(df4, ignore_index=True)
nyv = nyv.append(df5, ignore_index=True)
nyv['spam'] = np.where(nyv['spam'] == 'True', 1 ,0)
PViagra, PDeadline, PMillion, PAnd, PSex, PBeat, PDebt, POffer, PSpecial, PBest = (predictions[column] for column in predictions)
act = nyv["spam"]
for column in predictions:
    cm = confusion_matrix(act,predictions[column], labels=[1,0])
    print(column, ":", '\n',cm)

print()
    
for column in predictions:
    accuracy = accuracy_score(act, predictions[column])
    recall = recall_score(act, predictions[column])
    precision = precision_score(act,predictions[column])
    print(column,'accuracy',accuracy,'precision:', precision,'recall', recall)

Pred_viagra : 
 [[  0  94]
 [  1 486]]
Pred_deadline : 
 [[  0  94]
 [  0 487]]
Pred_million : 
 [[ 22  72]
 [  5 482]]
Pred_and : 
 [[  0  94]
 [  0 487]]
Pred_sex : 
 [[  0  94]
 [  0 487]]
Pred_beat : 
 [[  4  90]
 [  8 479]]
Pred_debt : 
 [[  8  86]
 [  3 484]]
Pred_offer : 
 [[  0  94]
 [  0 487]]
Pred_special : 
 [[  0  94]
 [  0 487]]
Pred_best : 
 [[  0  94]
 [  0 487]]

Pred_viagra accuracy 0.8364888123924269 precision: 0.0 recall 0.0
Pred_deadline accuracy 0.8382099827882961 precision: 0.0 recall 0.0
Pred_million accuracy 0.8674698795180723 precision: 0.8148148148148148 recall 0.23404255319148937
Pred_and accuracy 0.8382099827882961 precision: 0.0 recall 0.0
Pred_sex accuracy 0.8382099827882961 precision: 0.0 recall 0.0
Pred_beat accuracy 0.8313253012048193 precision: 0.3333333333333333 recall 0.0425531914893617
Pred_debt accuracy 0.846815834767642 precision: 0.7272727272727273 recall 0.0851063829787234
Pred_offer accuracy 0.8382099827882961 precision: 0.0 recall 0.0
Pred_spe

### 15.
Smoothing brought all the numbers down except recall, however it was by a small margin